name: gpt_test_gen
description: Dart test code generator with GPT-3.
version: 0.0.2
repository: https://github.com/Kurogoma4D/gpt_test_gen

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  args: ^2.4.0
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
