name: gpt_test_gen
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/Kurogoma4D/gpt_test_gen

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  args: ^2.4.0
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
